### ISSUE TITLE
A tribute to Dedicated Insanity

### ISSUE THREAD

**Issue by vtosh** [Road-block/LibGearScore-1.0#1]
Any chance this could be updated to include the requirements for "A Tribute to Dedicated Insanity"? 

Its much the same as Herald:
"Meet the criteria for A Tribute to Insanity without any raid member having used an item only obtainable from 25-player Coliseum, or any more powerful item"

**Comment by Road-block** [comment]
Yeah I was thinking about that, I'll add it.
I'm going to assume it's by item level again. 
Are there slot exclusions?

**Comment by Road-block** [comment]
I mean the old blue posts are rather confusing.
We also do not know

1. Changes they made during original wrath.
2. Potential changes for Classic.
So what's the current status?

Assuming it's similar to Herald where source of loot does not matter only itemlevel per slot.
245 or lower weapon / armor slots, except cloak which can be 258 (10m tribute loot)

Emblem vendor gear in? (245)
Crafts/BoE in? (245)
Onyxia gear in? (245)
25H cloaks (non tribute) in? (258)

**Comment by Road-block** [comment]
>A Tribute to Dedicated Insanity | 2009-09-17 17:58 | Blizzard Entertainment [Daelo](https://wowpedia.fandom.com/wiki/Daelo)

You can use:
Any item below item level 245.
The item level 245 set pieces that drop from 25-player Trial of the Crusader but also appear in the 10-player Tribute Chest.
Any gear that drops in 10-player [Trial of the Crusader](https://wowpedia.fandom.com/wiki/Trial_of_the_Crusader) or [Trial of the Grand Crusader](https://wowpedia.fandom.com/wiki/Trial_of_the_Grand_Crusader), including item level 245 Trial of the Grand Crusader drops and item level 258 cloaks from the 10-player Tribute Chest
Any item level 245 items purchased with [[Badges of Triumph]](https://wowpedia.fandom.com/wiki/Emblem_of_Triumph).
Any item level 245 [Bind on Equip](https://wowpedia.fandom.com/wiki/Bind_on_Equip) item, including crafted pieces.
You cannot use:

Any item level 245 item not included above (primarily [Bind on Pickup](https://wowpedia.fandom.com/wiki/Bind_on_Pickup) drops from 25-player Trial of the Crusader, but also notably [[Val'anyr]](https://wowpedia.fandom.com/wiki/Val%27anyr,_Hammer_of_Ancient_Kings)).
Any item over item level 245 except for the 10-player Tribute cloak.
Any higher item level loot introduced in future patches (25 player Onyxia 245s, Icecrown loot in the future, etc.)

If these requirements are still valid exactly as stated, I don't think I'll include this check.
It would require a loot database included in the library, as this is by item not by slot + itemlevel.

**Comment by vtosh** [comment]
No worries, thanks for looking into it.
